[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = 
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit ILI9341
    adafruit/Adafruit GFX Library
    SPI
    Bounce2
    paulstoffregen/OneWire @ ^2.3.7
    arduino-libraries/SD @ ^1.2.4
